### PR TITLE
Test: can we re-sync to upstream via a PR?

### PR DESCRIPTION
**Pull request by DavidOry**

### CODE REVIEW

**Comment by DavidOry** [comment]
@kulshresthaa: this *appears* to do the trick. I do not have write access (can you please give it to me). So please merge and see if this does what we think it's doing.

**Comment by DavidOry** [comment]
Oh, wait, perhaps we can do this another way.

**Comment by AshishKuls** [comment]
I found [this](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)!

**Comment by DavidOry** [comment]
I'll open up another PR bringing `install_fix` into our `development` branch to reflect the change in VisionEval. That seems cleaner and less circular.

**Comment by DavidOry** [comment]
> I found this!

Yes, that's the same as my option (a) in my email. Give that a go and we can stop kill this PR.

**Comment by AshishKuls** [comment]
> I'll open up another PR bringing `install_fix` into our `development` branch to reflect the change in VisionEval. That seems cleaner and less circular.

but then we are doing the same twice.. merging `install_fix` to `VisionEval/VisionEval-Dev` and then also merging `install_fix` into `wsp-sag/VisionEval-Dev`. Feel like we should do this only once :)

**Comment by DavidOry** [comment]
I agree. Give option (a) a try. I set up remotes in the `client_fhwa_vision_eval` repository.

**Comment by AshishKuls** [comment]
It worked. 
* git fetch upstream
* git checkout development
* git merge upstream/development
* git push

**Pull request closed without merging**
